=== JuanGonzalezCaminero/Election_Sim/schema/file.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Import/Export election file",
  "description": "File used to import/export all election data",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "date",
    "type",
    "configuration",
    "districts"
  ],
  "properties": {
    "date": {
      "type": "string",
      "format": "date"
    },
    "type": {
      "type": "string",
      "enum": [
        "regional",
        "congress",
        "senate",
        "local"
      ]
    },
    "configuration": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "threshold"
      ],
      "properties": {
        "threshold": {
          "type": "number",
          "minimum": 0,
          "maximum": 100
        }
      }
    },
    "districts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "voters",
          "representatives",
          "blank",
          "null",
          "candidatures"
        ],
        "properties": {
          "name": {
            "type": "string",
            "pattern": "^([a-z]|[A-Z]){1,30}$"
          },
          "voters": {
            "type": "number",
            "exclusiveMinimum": 0,
            "multipleOf": 1.0
          },
          "representatives": {
            "type": "number",
            "exclusiveMinimum": 0,
            "multipleOf": 1.0
          },
          "blank": {
            "type": "number",
            "minimum": 0,
            "multipleOf": 1.0
          },
          "null": {
            "type": "number",
            "minimum": 0,
            "multipleOf": 1.0
          },
          "candidatures": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "name",
                "abbr",
                "votes"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "pattern": "^([a-z]|[A-Z]){1}([a-z]|[A-Z]|[0-9]|-|_){0,69}$",
                  "maxLength": 70
                },
                "abbr": {
                  "type": "string",
                  "pattern": "^([a-z]|[A-Z]){1}([a-z]|[A-Z]|[0-9]|-|_){0,5}$"
                },
                "votes": {
                  "type": "number",
                  "minimum": 0,
                  "multipleOf": 1.0
                }
              }
            }
          }
        }
      }
    }
  }
}

=== JuanGonzalezCaminero/Election_Sim/main/static/election.json
{"date":"2020-01-25","type":"regional","configuration":{"threshold":0.03},"districts":[{"name":"Valladolid","voters":100000,"representatives":20,"blank":0,"null":0,"candidatures":[{"name":"PP","abbr":"PP","votes":50000},{"name":"PSOE","abbr":"PSOE","votes":50000}]},{"name":"Madrid","voters":3000000,"representatives":40,"blank":5000,"null":5000,"candidatures":[{"name":"PSOE","abbr":"PSOE","votes":2000000},{"name":"PP","abbr":"PP","votes":500000},{"name":"PAN","abbr":"PAN","votes":500000}]}]}

=== JuanGonzalezCaminero/Election_Sim/main/static/election_2.json
{"date":"2020-01-31","type":"congress","configuration":{"threshold":0.03},"districts":[{"name":"Oviedo","voters":200000,"representatives":15,"blank":0,"null":0,"candidatures":[{"name":"Partido3","abbr":"P3","votes":100000},{"name":"Partido2","abbr":"P2","votes":95000},{"name":"Partido1","abbr":"P1","votes":5000}]},{"name":"Madrid","voters":3000000,"representatives":40,"blank":5000,"null":5000,"candidatures":[{"name":"Partido Popular","abbr":"PP","votes":1000000},{"name":"Partido Socialista Obrero Español","abbr":"PSOE","votes":1500000},{"name":"Madrid Existe","abbr":"MAE","votes":490000}]},{"name":"Valladolid","voters":300000,"representatives":20,"blank":1000,"null":5000,"candidatures":[{"name":"Partido Popular","abbr":"PP","votes":200000},{"name":"Partido Socialista Obrero Español","abbr":"PSOE","votes":94000}]}]}

=== JuanGonzalezCaminero/Election_Sim/main/static/test-election.json
{"date":"2019-09-25","type":"local","configuration":{"threshold":0.03},"districts":[{"name":"Melilla","voters":1000,"representatives":1,"blank":10,"null":10,"candidatures":[{"name":"Teruel Existe","abbr":"TEXI","votes":100},{"name":"Estonia Existe","abbr":"EEXI","votes":150}]},{"name":"Ceuta","voters":1000,"representatives":1,"blank":10,"null":10,"candidatures":[{"name":"Teruel Existe","abbr":"TEXI","votes":100},{"name":"Estonia Existe","abbr":"EEXI","votes":200}]}]}
